// Copyright 2026 ühh and contributors. Licensed under MIT. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

type Bot struct {
	Id            string `json:"id"`
	BotName       string `json:"bot_name"`
	MeetingUrl    string `json:"meeting_url"`
	JoinAt        string `json:"join_at"`
	StatusChanges string `json:"status_changes"`
}

type Recording struct {
	Id          string `json:"id"`
	Status      string `json:"status"`
	CreatedAt   string `json:"created_at"`
	StartedAt   string `json:"started_at"`
	CompletedAt string `json:"completed_at"`
}
