// Copyright 2026 ühh and contributors. Licensed under MIT. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newBotsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "bots",
		Short:       "Send bots into meetings, check on them, and pull what they captured.",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newBotsCreateCmd(flags))
	cmd.AddCommand(newBotsGetCmd(flags))
	cmd.AddCommand(newBotsLeaveCmd(flags))
	cmd.AddCommand(newBotsListCmd(flags))
	cmd.AddCommand(newBotsTranscriptCmd(flags))
	return cmd
}
