// Copyright 2026 ühh and contributors. Licensed under MIT. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
//
// This is a trimmed copy of the generator's data-source resolver. The
// generated version supports --data-source live|local|auto against a local
// SQLite sync store; this demo CLI has no offline store (there is nothing to
// sync without an API key), so every read goes straight to the live API.
// Function names and signatures match the generator's output so the command
// files under bots_*.go and promoted_recordings.go did not need to change.

package cli

import (
	"context"
	"encoding/json"
	"io"

	"recall/internal/client"
)

// resolveRead issues a live GET and returns the response plus provenance.
func resolveRead(ctx context.Context, c *client.Client, flags *rootFlags, resourceType string, isList bool, path string, params map[string]string, headers map[string]string, hintWriter io.Writer) (json.RawMessage, DataProvenance, error) {
	return resolveReadWithResponsePath(ctx, c, flags, resourceType, isList, path, params, headers, "", hintWriter)
}

func resolveReadWithResponsePath(ctx context.Context, c *client.Client, flags *rootFlags, resourceType string, isList bool, path string, params map[string]string, headers map[string]string, responsePath string, hintWriter io.Writer) (json.RawMessage, DataProvenance, error) {
	return resolveReadWithStrategyAndResponsePath(ctx, c, flags, "live", resourceType, isList, path, params, headers, responsePath, hintWriter)
}

// resolveReadWithStrategy ignores strategy (kept for call-site compatibility
// with the generator's shape) and always reads live.
func resolveReadWithStrategy(ctx context.Context, c *client.Client, flags *rootFlags, strategy string, resourceType string, isList bool, path string, params map[string]string, headers map[string]string, hintWriter io.Writer) (json.RawMessage, DataProvenance, error) {
	return resolveReadWithStrategyAndResponsePath(ctx, c, flags, strategy, resourceType, isList, path, params, headers, "", hintWriter)
}

func resolveReadWithStrategyAndResponsePath(ctx context.Context, c *client.Client, flags *rootFlags, strategy string, resourceType string, isList bool, path string, params map[string]string, headers map[string]string, responsePath string, hintWriter io.Writer) (json.RawMessage, DataProvenance, error) {
	data, err := c.GetWithHeaders(ctx, path, params, headers)
	if err != nil {
		return nil, DataProvenance{}, err
	}
	if err := assertLiveJSONBody(data); err != nil {
		return nil, DataProvenance{}, err
	}
	data = applyResponsePath(data, responsePath)
	return data, DataProvenance{Source: "live", ResourceType: resourceType}, nil
}

// resolvePaginatedRead issues a live paginated GET.
func resolvePaginatedRead(ctx context.Context, c *client.Client, flags *rootFlags, resourceType string, path string, params map[string]string, headers map[string]string, fetchAll bool, cursorParam, paginationType, limitParam string, defaultPageSize int, nextCursorPath, hasMoreField string, hintWriter io.Writer) (json.RawMessage, DataProvenance, error) {
	data, err := paginatedGet(ctx, c, path, params, headers, fetchAll, cursorParam, paginationType, limitParam, defaultPageSize, nextCursorPath, hasMoreField)
	if err != nil {
		return nil, DataProvenance{}, err
	}
	if err := assertLiveJSONBody(data); err != nil {
		return nil, DataProvenance{}, err
	}
	return data, DataProvenance{Source: "live", ResourceType: resourceType}, nil
}

// writeMutationResponseToStore is a no-op in this demo CLI (no local store to
// write through to). Kept so bots_create.go / bots_leave.go call sites match
// the generator's shape without hand-editing generated files.
func writeMutationResponseToStore(ctx context.Context, resourceType string, data json.RawMessage, responsePath string) {
}
